/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2014-03-21 18:58:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/custom-tags.tld", Long.valueOf(1395397053473L));
    _jspx_dependants.put("/WEB-INF/struts-tags.tld", Long.valueOf(1385006053243L));
    _jspx_dependants.put("/WEB-INF/tiles-jsp.tld", Long.valueOf(1385006054786L));
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1385006053262L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fyuidatatable_0026_005ftableWithCheckBox_005fsortableColumns_005fsortByColumns_005freturnValueOfColumns_005fqueryJsonDataUrl_005fcontainerId_005fcolumns;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fyuidatatable_0026_005ftableWithCheckBox_005fsortableColumns_005fsortByColumns_005freturnValueOfColumns_005fqueryJsonDataUrl_005fcontainerId_005fcolumns = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fui_005fyuidatatable_0026_005ftableWithCheckBox_005fsortableColumns_005fsortByColumns_005freturnValueOfColumns_005fqueryJsonDataUrl_005fcontainerId_005fcolumns.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Menu item -->\r\n");
      out.write("<b>");
      if (_jspx_meth_s_005ftext_005f0(_jspx_page_context))
        return;
      out.write(":</b>\r\n");
      out.write("<div id=\"comments\"></div>\r\n");
      if (_jspx_meth_ui_005fyuidatatable_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- <table> -->\r\n");
      out.write("<!-- \t<tr><td> -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- \t</td></tr> -->\r\n");
      out.write("<!-- </table> -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction setupTodayMenu(selectedItems){\r\n");
      out.write("\t\talert(\"fff\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f0 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    _jspx_th_s_005ftext_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftext_005f0.setParent(null);
    // /jsp/comment.jsp(9,3) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftext_005f0.setName("vietpage.lastcomment");
    int _jspx_eval_s_005ftext_005f0 = _jspx_th_s_005ftext_005f0.doStartTag();
    if (_jspx_th_s_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
    return false;
  }

  private boolean _jspx_meth_ui_005fyuidatatable_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:yuidatatable
    com.vnsoft.server.tags.yui.YUIDataTableTag _jspx_th_ui_005fyuidatatable_005f0 = (com.vnsoft.server.tags.yui.YUIDataTableTag) _005fjspx_005ftagPool_005fui_005fyuidatatable_0026_005ftableWithCheckBox_005fsortableColumns_005fsortByColumns_005freturnValueOfColumns_005fqueryJsonDataUrl_005fcontainerId_005fcolumns.get(com.vnsoft.server.tags.yui.YUIDataTableTag.class);
    _jspx_th_ui_005fyuidatatable_005f0.setPageContext(_jspx_page_context);
    _jspx_th_ui_005fyuidatatable_005f0.setParent(null);
    // /jsp/comment.jsp(11,0) name = columns type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setColumns("content:Nội dung tin nhắn,postedBy:Người nhắn,postedDate:Ngày nhắn");
    // /jsp/comment.jsp(11,0) name = containerId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setContainerId("comments");
    // /jsp/comment.jsp(11,0) name = queryJsonDataUrl type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setQueryJsonDataUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/comment?comId=${companyInfo.id }&action=getcomments&", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /jsp/comment.jsp(11,0) name = sortableColumns type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setSortableColumns("postedBy");
    // /jsp/comment.jsp(11,0) name = sortByColumns type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setSortByColumns("postedBy");
    // /jsp/comment.jsp(11,0) name = tableWithCheckBox type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setTableWithCheckBox(false);
    // /jsp/comment.jsp(11,0) name = returnValueOfColumns type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ui_005fyuidatatable_005f0.setReturnValueOfColumns("content");
    int _jspx_eval_ui_005fyuidatatable_005f0 = _jspx_th_ui_005fyuidatatable_005f0.doStartTag();
    if (_jspx_eval_ui_005fyuidatatable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_ui_005fyuidatatable_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_ui_005fyuidatatable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fui_005fyuidatatable_0026_005ftableWithCheckBox_005fsortableColumns_005fsortByColumns_005freturnValueOfColumns_005fqueryJsonDataUrl_005fcontainerId_005fcolumns.reuse(_jspx_th_ui_005fyuidatatable_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fui_005fyuidatatable_0026_005ftableWithCheckBox_005fsortableColumns_005fsortByColumns_005freturnValueOfColumns_005fqueryJsonDataUrl_005fcontainerId_005fcolumns.reuse(_jspx_th_ui_005fyuidatatable_005f0);
    return false;
  }
}
